### ISSUE TITLE
config.env appears in the repo.

### ISSUE THREAD

**Issue by dongli-liu** [Hi-kue/Comp229_Milestone#12]
server/config.env
I think it should be removed.
I have added *.env to .gitignore. But it should be cleanup up in history.

**Comment by Hi-kue** [comment]
Yeah those changes are due to the fact that Jenny was using config.env rather then just .env, which is a bit of an issue but it should be fine by next merge.

**Comment by Hi-kue** [comment]
Still not sure where the config.env gets used but Im sure it will be safe to remove
