### ISSUE TITLE
The [Documentation] link does not work

### ISSUE THREAD

**Issue by dongli-liu** [Hi-kue/Comp229_Milestone#4]
Hi, @Hi-kue 

README.md - right under the logo - [Documentation] link can direct to the correct webpage.

The current url address for it is: https://github.com/Hi-kue/Wizstack/blob/main/url

Please help to fix it. 

Thank you.

**Comment by Hi-kue** [comment]
Thanks for letting me know @dongli-liu, should be a minor fix ill see what I can do. It is the [Documentation] Link you are referring to, thats just a placeholder link at the moment I would need to finish creating the external doc website first and publish it

**Comment by Hi-kue** [comment]
This issue has been fixed during our previous submission and is closed.
